"""The index constituent lists, shared by `equity-universe` and
`intl-equity-prices`.

Leading underscore so the registry's auto-discovery skips this module. The
lists are committed files (data/constituents/*.csv), regenerated by
scripts/refresh_index_constituents.py — see that script for where they come
from and why they are not scraped at every run.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List

import pandas as pd

from ..config import DATA_DIR

CONSTITUENTS_DIR = DATA_DIR / "constituents"

#: market id -> (display name, file). SP500 is not here: its tickers are
#: data/tickers.csv and its prices sp500-prices', unchanged.
MARKETS = {
    "CAC40": ("CAC 40", "cac40.csv"),
    "DAX": ("DAX", "dax.csv"),
    "FTSE100": ("FTSE 100", "ftse100.csv"),
    "NIKKEI225": ("Nikkei 225", "nikkei225.csv"),
}

#: Quote units Yahoo uses that are a fraction of the ISO currency: London
#: lines quote in pence (GBp). Prices are stored in the ISO currency.
SUBUNITS = {"GBp": ("GBP", 100.0), "GBX": ("GBP", 100.0), "ZAc": ("ZAR", 100.0), "ILA": ("ILS", 100.0)}


@dataclass(frozen=True)
class Member:
    market: str
    ticker: str
    name: str
    kind: str  # "index" | "equity"
    quote_currency: str  # as Yahoo quotes it, e.g. "GBp"
    as_of: str

    @property
    def currency(self) -> str:
        """The ISO currency prices are stored in."""
        return SUBUNITS.get(self.quote_currency, (self.quote_currency, 1.0))[0]

    @property
    def divisor(self) -> float:
        return SUBUNITS.get(self.quote_currency, (self.quote_currency, 1.0))[1]


def members(market: str) -> List[Member]:
    path = CONSTITUENTS_DIR / MARKETS[market][1]
    frame = pd.read_csv(path, dtype=str, keep_default_na=False)
    return [
        Member(market, r.ticker, r.name, r.kind, r.quote_currency, r.as_of)
        for r in frame.itertuples(index=False)
    ]


def all_members() -> List[Member]:
    return [m for market in MARKETS for m in members(market)]
